---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: mon
  annotations:
    flux.weave.works/ignore: 'false'
    flux.weave.works/automated: 'false'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.0.1
        env:
        - name: SERVER_NAME
          value: 's.desertbluffs.com'
        - name: ELASTICSEARCH_HOSTS
          value: 'http://elasticsearch:9200'

