kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: nzbhydra
  namespace: media
spec:
  podSelector:
    matchLabels:
      app: nzbhydra
  ingress:
  - ports:
    - port: 5075
    from: []
