---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nzbhydra
  namespace: media
  annotations:
    flux.weave.works/tag.nzbhydra: regexp:^[0-9]+$
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nzbhydra
    spec:
      volumes:
      - name: nzbhydra-config
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:nzbhydra
          targetPortal: 192.168.220.149
          lun: 1
          fsType: ext4
      containers:
      - name: nzbhydra
        image: linuxserver/hydra:151
        volumeMounts:
        - name: nzbhydra-config
          subPath: config
          mountPath: /config
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - containerPort: 5075
          name: nzbhydra
        readinessProbe:
          tcpSocket:
            port: nzbhydra
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: nzbhydra
          initialDelaySeconds: 15
          periodSeconds: 20
