apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nzbhydra
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override nzbhydra.media.svc.cluster.local:5075;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  tls:
  - hosts:
    - i.desertbluffs.com
  rules:
  - host: i.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nzbhydra
          servicePort: nzbhydra
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nzbhydra-oauth2
  namespace: media
spec:
  tls:
  - hosts:
    - i.desertbluffs.com
  rules:
  - host: i.desertbluffs.com
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: oauth2-proxy
          servicePort: oauth2-proxy
