apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nzbhydra
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - i.desertbluffs.com
  rules:
  - host: i.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nzbhydra
          servicePort: nzbhydra
