---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ddclient
  namespace: default
  annotations:
    flux.weave.works/tag.ddclient: regexp:^[0-9]+$
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ddclient
    spec:
      volumes:
      - name: config
        secret:
          secretName: ddclient
      containers:
      - name: ddclient
        image: linuxserver/ddclient:144
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
