apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient
  namespace: default
spec:
  encryptedData:
    ddclient.conf: AgAYEGXgv30Jz9FI1w+pPrwAxkoT9XUGpXccKJHLvLs67yPlnObRv2YrR2rTgcZM08lc82et91FBD1pmwqEJpQ3SMldf08W0IESnOAQx0XE4zvZNih5lCTxrgBRGQYbfoqwgfsVrHNzqf9zKaw4kATxGiVkXpBcfT1ftA1WxqF+1xNKfohcWpqSFmQyJuvV7szctFJkDQG2WLEgaBpaqdz24xr4i6XQorLrCQJOrbJezsgqKJzR4yUQpaOF1Owz03bCkqTu475YYiCEg7PZF9FjBtd9Qakl0qIbm1kfzz254ZzzJjE2JN46xXnLa0T+K8snWt61H/IpUAbF9CNtQt+aHxuGfygo5MnKI4fZuT3Ig40Dna6SWHyuUykEWQ6e5BmsOn+NNSXh3rTpZhD1UoPhhr1lmnn6dttTZXcYhoeeIadjofqi3YX5aczNP2+Uu66Jmj/1bj4siPaTpLSuFxVNjWTvM/VetXNnYrVQg3ahyRuUVCV9CY/Vts5cavgw6KHrUdNpD7yHwcP6pyzqJZA/P9isjV1WG+GlreWIynJZxvl9CiBjQ8F12LkocP3yMdR2ngYSkDyri5I0S1IfygMs+aJzkt5T2Q2hJl17mblhaHPqlgXA0eLAMUzwJkCgiHRO+qXxpxYLYXs4hco3WVn6aU8ONgmUied5wK1FX3VK7ZXtva2woqvEFa0WVLtMJPpnlZU4+kp5W7Q9URaUQYuYZp8beBLKl+ESUjO5wpeQtHUMN2AT27Hf6pFQeEn1A73Pvlxgq5jVDsZaJLrsRaTXCWlw7C+Cfs7BR66Q3JLaOV1xRj5Li5ES+D7469hegE+IvO3RXPz3LC3LJXYiRCL26BYZm0ai72n/DgZ0NnSowHFEAkf2H3kBjQIj8OuJ/QW5Afx9eAxEDy+YNfSBoBdyd/9L/J3N+1H98OXTT8kmg60kxweR8P33bz57Mcbf9QSRl3mCcudg5zBJrdC8saTTFTccEgxMSJXK++iNYwLV7AS8ATwUGxDQW+Zfm2dA=

