apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient
  namespace: default
spec:
  encryptedData:
    ddclient.conf: AgCb8TQQyXlmXbFPQ1qxS9BAOEDeiuBDAwCj7bCAvQcB2URe0UGETxvdhYwejgq2JBxTW8mx78EhA1HWX5/7wBzVboikEdvvpvS78BPkdXuNoMNt4ol+tUsYqywbkXcRAR822OpBnwsTFwTsBZmGLfEi7tzS8b+sL1Koc5yVk0sJNP9reEBuVuuvt+ct6EkP1qU/8HwPoiR9fOipFiHUn6jxpuKuCVlJbs0QXHZRrRuIPXycLugpNgkCOoQ27Y4uOKQZNT6hCstj/PjpgSOdj+9a/frS4xyxOdZwPXyNSyouk9GLeZ/Dc3rcrKGvlGr9lzOoPL4gTo3SjUvHjHFrMNBo94RPu2gevHi5klirRxBWXPl7B/8+88gk13ZHlmddUMX1oe89oDuQNkfMj9sTMm0xQCGwE68Z3DI7XvWcOdF4ozyd1VpRg+k+zvug08PNgab/oShLvy0tLWi8v/yaW7d8K4HogHHQwYOr1T8tCUJIrI/RmNVSRde5I+ejQa6YvjCkPxgcIEU2201fbGzhaB3RSfJW/a8EgutBH6DLl1by6/BzpKziN83pM56oabZ6AvwrcttlBPfKvQU4EyEeCyqVc2LM0jf32M8ztC9qVKXZEu0Jk63SSQnXovd7owOEEF0MyX09rZphwDvtzirKGbOO/8nm3w9JoRf2kA5flhCiCB1/82XRiFVG+UPhiGGWNmBv1ss/pKuE+xK076rTRyLgU+FJ1eK0S7mtzJlF4Rzf5jdstM8+E9OpTLdVEo8Dm9h75StvOXrpGFPSKXLXvExTfP6k0p32XG8eZKi1jngmODw3a13DaKWs43nL2oNMdBr2KQ/oCGTMBllsAK7orT92m/o59BJHDkEwSVvgZMxKKrZ/ViBewIHwL0Fl/vneSXu9Pao8wBx/JkgwQcAN1uO3fcaoFDsL+oHELFXOQLdMoB5s3mVRqV9FWSJo0o+QiMSMGHLP4YuLvP8uRdjtqAkDHVcdEiRZpjcr+MmrX22J9okLfOpymPxvRIVcz8ic9Yre0YYgOlfinB1kJ6+RLdeSfM3j/tJkVHB0RXTNv9n4BXg15QnjaPgaCpeGKB5QK6ablet6SlcWFrs9K6MS91HHejj63gcnc0/YSs2dvf70TLgNOOU=

