apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
      - name: anime
        persistentVolumeClaim:
          claimName: anime
      - name: sonarr
        hostPath:
          path: /akasha/sonarr
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: oauth2-proxy
        secret:
          secretName: oauth2-proxy
      - name: rtc
        hostPath:
          path: /dev/rtc
      - name: tv
        persistentVolumeClaim:
          claimName: tv
      containers:
      - name: sonarr
        image: linuxserver/sonarr
        imagePullPolicy: Always
        volumeMounts:
        - name: sonarr
          subPath: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        - name: anime
          mountPath: /media/anime
        - name: tv
          mountPath: /media/tv
        - name: rtc
          mountPath: /dev/rtc
          readOnly: true
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: sonarr
          containerPort: 8989
        livenessProbe:
          httpGet:
            path: /
            port: sonarr
          initialDelaySeconds: 60
          periodSeconds: 5
      - name: oauth2-proxy
        image: a5huynh/oauth2_proxy
        ports:
        - containerPort: 4180
        volumeMounts:
        - mountPath: /etc/oauth2-proxy
          name: oauth2-proxy
          readOnly: true
        args:
        - "-upstream=http://localhost:8989/"
        - "-cookie-domain=sonarr.desertbluffs.com"
        - "-redirect-url=https://sonarr.desertbluffs.com/oauth2/callback"
        - "-http-address=0.0.0.0:4180"
        - "-config=/etc/oauth2-proxy/config"
        - "-authenticated-emails-file=/etc/oauth2-proxy/authenticated-emails"
        - "-cookie-secure=true"
        - "-cookie-expire=168h0m"
        - "-cookie-refresh=60m"
        - "-skip-provider-button=true"
