apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: biggs.radoncanyon.com
      volumes:
      - name: sonarr
        hostPath:
          path: /dockerfs/sonarr
      - name: downloads-nas2
        persistentVolumeClaim:
          claimName: downloads-nas2
      - name: anime-nas2
        persistentVolumeClaim:
          claimName: anime-nas2
      - name: tv-nas2
        persistentVolumeClaim:
          claimName: tv-nas2
      containers:
      - name: sonarr
        image: linuxserver/sonarr:129
        volumeMounts:
        - name: sonarr
          subPath: config
          mountPath: /config
        - name: anime-nas2
          mountPath: /media/anime/nas2
        - name: tv-nas2
          mountPath: /media/tv/nas2
        - name: downloads-nas2
          mountPath: /downloads/nas2
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: sonarr
          containerPort: 8989
        readinessProbe:
          tcpSocket:
            port: sonarr
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: sonarr
          initialDelaySeconds: 15
          periodSeconds: 20
