apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: biggs.radoncanyon.com
      volumes:
      - name: media
        hostPath:
          path: /mnt/media
      - name: sonarr
        hostPath:
          path: /dockerfs/sonarr
      - name: rtc
        hostPath:
          path: /dev/rtc
      containers:
      - name: sonarr
        image: linuxserver/sonarr
        volumeMounts:
        - name: sonarr
          subPath: config
          mountPath: /config
        - name: media
          subPath: downloads
          mountPath: /downloads
        - name: media
          subPath: anime
          mountPath: /media/anime
        - name: media
          subPath: tv
          mountPath: /media/tv
        - name: rtc
          mountPath: /dev/rtc
          readOnly: true
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: sonarr
          containerPort: 8989
        livenessProbe:
          httpGet:
            path: /
            port: sonarr
          initialDelaySeconds: 60
          periodSeconds: 5

