apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: biggs
      volumes:
        - name: sonarr-config
          hostPath:
            path: /dockerfs/sonarr/config
        - name: downloads
          hostPath:
            path: /mnt/downloads
        - name: media
          hostPath:
            path: /mnt/media
        - name: rtc
          hostPath:
            path: /dev/rtc
      containers:
      - name: sonarr
        image: linuxserver/sonarr
        volumeMounts:
        - mountPath: /config
          name: sonarr-config
        - mountPath: /downloads
          name: downloads
        - mountPath: /media
          name: media
        - mountPath: /dev/rtc
          name: rtc
          readOnly: true
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: sonarr
          containerPort: 8989
