apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarr
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - sonarr.desertbluffs.com
    secretName: sonarr-tls
  rules:
  - host: sonarr.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sonarr
          servicePort: 80
