---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr
  labels:
    pv: sonarr
spec:
  capacity:
    storage: 100Ti
  accessModes:
  - ReadWriteOnce
  nfs:
    server: freenas.radoncanyon.com
    path: "/mnt/etank/dockerfs/sonarr"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Ti
  selector:
    matchLabels:
      pv: sonarr
