apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tautulli
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      nodeSelector:
        kubernetes.io/hostname: wedge.radoncanyon.com
      volumes:
      - name: tautulli
        hostPath:
          path: /dockerfs/plexpy
      - name: pms
        hostPath:
          path: /dockerfs/pms
      containers:
      - name: tautulli
        image: linuxserver/tautulli:136
        volumeMounts:
        - name: tautulli
          subPath: config
          mountPath: /config
        - name: pms
          subPath: config/Library/Application Support/Plex Media Server/Logs
          mountPath: /logs
          readOnly: true
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: tautulli
          containerPort: 8181
        readinessProbe:
          tcpSocket:
            port: tautulli
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: tautulli
          initialDelaySeconds: 15
          periodSeconds: 20
