kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: flux-memcache
  namespace: default
spec:
  podSelector:
    matchLabels:
      name: memcached
  ingress:
  - ports:
    - port: 11211
    from:
    - namespaceSelector:
        matchLabels:
          name: default
      podSelector:
        matchLabels:
          name: flux
