apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv-nas2
  labels:
    name: tv-nas2
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas2.radoncanyon.com
    path: "/mnt/etank/media/tv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-nas2
  labels:
    name: movies-nas2
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas2.radoncanyon.com
    path: "/mnt/etank/media/movies"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies4k-nas2
  labels:
    name: movies4k-nas2
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas2.radoncanyon.com
    path: "/mnt/etank/media/movies4k"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: anime-nas2
  labels:
    name: anime-nas2
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas2.radoncanyon.com
    path: "/mnt/etank/media/anime"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-nas1
  labels:
    name: downloads-nas1
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas1.radoncanyon.com
    path: "/mnt/etank/scratch/downloads"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-nas2
  labels:
    name: downloads-nas2
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas2.radoncanyon.com
    path: "/mnt/etank/scratch/downloads"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-nas1
  labels:
    name: music-nas1
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas1.radoncanyon.com
    path: "/mnt/etank/media/music"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-nas2
  labels:
    name: music-nas2
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas2.radoncanyon.com
    path: "/mnt/etank/media/music"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  labels:
    name: nextcloud-data
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas2.radoncanyon.com
    path: "/mnt/etank/nextcloud"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge
  labels:
    name: deluge
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas1.radoncanyon.com
    path: "/mnt/etank/scratch/downloads/deluge"
