apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nzbget
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: nzbget
    servicePort: 6789
  tls:
  - hosts:
    - c.desertbluffs.com
