apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  namespace: default
  labels:
    name: media
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.114
    path: "/mnt/etank/media"
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scratch
  namespace: default
  labels:
    name: scratch
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.149
    path: "/mnt/etank/scratch"
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: roms
  namespace: default
  labels:
    name: roms
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.149
    path: "/mnt/etank/scratch/roms"
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge
  namespace: default
  labels:
    name: deluge
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.149
    path: "/mnt/etank/scratch/downloads/deluge"
  mountOptions:
    - nfsvers=4.1
