apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-redis
  namespace: default
data:
  redis.conf: |
    # 0 = do not listen on a port
    port 0

    # listen on localhost only
    bind 127.0.0.1

    # create a unix domain socket to listen on
    unixsocket /tmp/redis.sock

    # set permissions for the socket
    unixsocketperm 755
