apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-redis
  namespace: default
data:
  redis.conf: |
    port 6379

    # listen on localhost only
    bind 127.0.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-php-ini
  namespace: default
data:
  php.ini: |
    [PHP]
    engine = On
    short_open_tag = Off
    precision = 14
    output_buffering = 4096
    zlib.output_compression = Off
    implicit_flush = Off
    unserialize_callback_func =
    serialize_precision = -1
    disable_functions =
    disable_classes =
    zend.enable_gc = On
    expose_php = Off
    max_execution_time = 30
    max_input_time = 60
    memory_limit=1G
    error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
    display_errors = Off
    display_startup_errors = Off
    log_errors = On
    log_errors_max_len = 1024
    ignore_repeated_errors = Off
    ignore_repeated_source = Off
    report_memleaks = On
    html_errors = On
    variables_order = "GPCS"
    request_order = "GP"
    register_argc_argv = Off
    auto_globals_jit = On
    post_max_size = 10G
    auto_prepend_file =
    auto_append_file =
    default_mimetype = "text/html"
    default_charset = "UTF-8"
    include_path = ".:/usr/share/php7"
    doc_root =
    user_dir =
    enable_dl = Off
    file_uploads = On
    upload_max_filesize = 10G
    max_file_uploads = 20
    allow_url_fopen = On
    allow_url_include = Off
    default_socket_timeout = 60
    [CLI Server]
    cli_server.color = On
    [Date]
    [filter]
    [iconv]
    [imap]
    [intl]
    [sqlite3]
    sqlite3.defensive = 1
    [Pcre]
    [Pdo]
    [Pdo_mysql]
    pdo_mysql.cache_size = 2000
    pdo_mysql.default_socket=
    [Phar]
    [mail function]
    SMTP = localhost
    smtp_port = 25
    mail.add_x_header = Off
    [ODBC]
    odbc.allow_persistent = On
    odbc.check_persistent = On
    odbc.max_persistent = -1
    odbc.max_links = -1
    odbc.defaultlrl = 4096
    odbc.defaultbinmode = 1
    [Interbase]
    ibase.allow_persistent = 1
    ibase.max_persistent = -1
    ibase.max_links = -1
    ibase.timestampformat = "%Y-%m-%d %H:%M:%S"
    ibase.dateformat = "%Y-%m-%d"
    ibase.timeformat = "%H:%M:%S"
    [MySQLi]
    mysqli.max_persistent = -1
    mysqli.allow_persistent = On
    mysqli.max_links = -1
    mysqli.cache_size = 2000
    mysqli.default_port = 3306
    mysqli.default_socket =
    mysqli.default_host =
    mysqli.default_user =
    mysqli.default_pw =
    mysqli.reconnect = Off
    [mysqlnd]
    mysqlnd.collect_statistics = On
    mysqlnd.collect_memory_statistics = Off
    [OCI8]
    [PostgreSQL]
    pgsql.allow_persistent = On
    pgsql.auto_reset_persistent = Off
    pgsql.max_persistent = -1
    pgsql.max_links = -1
    pgsql.ignore_notice = 0
    pgsql.log_notice = 0
    [bcmath]
    bcmath.scale = 0
    [browscap]
    [Session]
    session.save_handler = files
    session.use_strict_mode = 0
    session.use_cookies = 1
    session.use_only_cookies = 1
    session.name = PHPSESSID
    session.auto_start = 0
    session.cookie_lifetime = 0
    session.cookie_path = /
    session.cookie_domain =
    session.cookie_httponly =
    session.serialize_handler = php
    session.gc_probability = 1
    session.gc_divisor = 1000
    session.gc_maxlifetime = 1440
    session.referer_check =
    session.cache_limiter = nocache
    session.cache_expire = 180
    session.use_trans_sid = 0
    session.sid_length = 26
    session.trans_sid_tags = "a=href,area=href,frame=src,form="
    session.sid_bits_per_character = 5
    [Assertion]
    zend.assertions = -1
    [COM]
    [mbstring]
    [gd]
    [exif]
    [Tidy]
    tidy.clean_output = Off
    [soap]
    soap.wsdl_cache_enabled=1
    soap.wsdl_cache_dir="/tmp"
    soap.wsdl_cache_ttl=86400
    soap.wsdl_cache_limit = 5
    [sysvshm]
    [ldap]
    ldap.max_links = -1
    [dba]
    [opcache]
    opcache.enable=1
    opcache.enable_cli=1
    opcache.enable=1
    opcache.enable_cli=1
    opcache.memory_consumption=128
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=10000
    opcache.revalidate_freq=1
    opcache.save_comments=1
    opcache.enable=1
    opcache.enable_cli=1
    [curl]
    [openssl]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-php-opcache-config
  namespace: default
data:
  10-opcache.ini: |
    opcache.enable=1
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=10000
    opcache.memory_consumption=128
    opcache.save_comments=1
    opcache.revalidate_freq=1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-php-fpm
  namespace: default
data:
  www.conf: |
    [www]
    user = abc
    group = abc
    listen = 127.0.0.1:9000
    pm = static
    pm.max_children = 64
    pm.max_requests = 1000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-mariadb
  namespace: default
data:
  custom.cnf: |
    ## custom configuration file, please be aware that changing options here may break things

    [mysqld_safe]
    nice    = 0

    [mysqld]
    max_connections   = 300
    connect_timeout   = 5
    wait_timeout    = 600
    max_allowed_packet  = 16M
    thread_cache_size       = 128
    sort_buffer_size  = 4M
    bulk_insert_buffer_size = 16M
    tmp_table_size    = 32M
    max_heap_table_size = 32M
    transaction_isolation   = READ-COMMITTED

    binlog_format=row
    #
    # * MyISAM
    #
    # This replaces the startup script and checks MyISAM tables if needed
    # the first time they are touched. On error, make copy and try a repair.
    myisam_recover_options = BACKUP
    key_buffer_size   = 128M
    #open-files-limit = 2000
    table_open_cache  = 400
    myisam_sort_buffer_size = 512M
    concurrent_insert = 2
    read_buffer_size  = 2M
    read_rnd_buffer_size  = 1M
    #
    # * Query Cache Configuration
    #
    # Cache only tiny result sets, so we can fit more in the query cache.
    query_cache_limit   = 128K
    query_cache_size    = 64M
    # for more write intensive setups, set to DEMAND or OFF
    #query_cache_type   = DEMAND
    #
    # * Logging and Replication
    #
    # Both location gets rotated by the cronjob.
    # Be aware that this log type is a performance killer.
    # As of 5.1 you can enable the log at runtime!
    #general_log_file        = /config/log/mysql/mysql.log
    #general_log             = 1
    #
    # Error logging goes to syslog due to /etc/mysql/conf.d/mysqld_safe_syslog.cnf.
    #
    # we do want to know about network errors and such
    log_warnings    = 2
    #
    # Enable the slow query log to see queries with especially long duration
    #slow_query_log[={0|1}]
    slow_query_log_file = /config/log/mysql/mariadb-slow.log
    long_query_time = 10
    #log_slow_rate_limit  = 1000
    log_slow_verbosity  = query_plan

    #log-queries-not-using-indexes
    #log_slow_admin_statements
    #
    # The following can be used as easy to replay backup logs or for replication.
    # note: if you are setting up a replication slave, see README.Debian about
    #       other settings you may need to change.
    #server-id    = 1
    #report_host    = master1
    #auto_increment_increment = 2
    #auto_increment_offset  = 1
    log_bin     = /config/log/mysql/mariadb-bin
    log_bin_index   = /config/log/mysql/mariadb-bin.index
    # not fab for performance, but safer
    #sync_binlog    = 1
    expire_logs_days  = 3
    max_binlog_size         = 100M
    # slaves
    #relay_log    = /config/log/mysql/relay-bin
    #relay_log_index  = /config/log/mysql/relay-bin.index
    #relay_log_info_file  = /config/log/mysql/relay-bin.info
    #log_slave_updates
    #read_only
    #
    # If applications support it, this stricter sql_mode prevents some
    # mistakes like inserting invalid dates etc.
    #sql_mode   = NO_ENGINE_SUBSTITUTION,TRADITIONAL
    #
    # * InnoDB
    #
    # InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
    # Read the manual for more InnoDB related options. There are many!
    default_storage_engine  = InnoDB
    # you can't just change log file size, requires special procedure
    #innodb_log_file_size = 50M
    innodb_buffer_pool_size = 1G
    innodb_log_buffer_size  = 8M
    innodb_file_per_table = 1
    innodb_open_files = 400
    innodb_io_capacity  = 4000
    innodb_flush_method = O_DIRECT
    innodb_doublewrite      = 0

    #
    # * Security Features
    #
    # Read the manual, too, if you want chroot!
    # chroot = /var/lib/mysql/
    #
    # For generating SSL certificates I recommend the OpenSSL GUI "tinyca".
    #
    # ssl-ca=/etc/mysql/cacert.pem
    # ssl-cert=/etc/mysql/server-cert.pem
    # ssl-key=/etc/mysql/server-key.pem

    #
    # * Galera-related settings
    #
    [galera]
    # Mandatory settings
    #wsrep_on=ON
    #wsrep_provider=
    #wsrep_cluster_address=
    #default_storage_engine=InnoDB
    #innodb_autoinc_lock_mode=2
    #
    # Allow server to accept connections on all interfaces.
    #
    #bind-address=0.0.0.0
    #
    # Optional setting
    #wsrep_slave_threads=1
    #innodb_flush_log_at_trx_commit=0

    [mysqldump]
    quick
    quote-names
    max_allowed_packet  = 16M

    [mysql]
    #no-auto-rehash # faster start of mysql but no tab completion

    [isamchk]
    key_buffer_size   = 16M
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-crontabs
  namespace: default
data:
  root: |
    */15 * * * * s6-setuidgid abc php7 -f /config/www/nextcloud/cron.php
    @hourly s6-setuidgid abc nice php7 -f /config/www/nextcloud/occ -- preview:pre-generate >> /data/preview.log
