apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-redis
  namespace: default
  annotations:
    flux.weave.works/ignore: 'true'
data:
  redis.conf: |
    port 6379

    # listen on localhost only
    bind 127.0.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-php-fpm
  namespace: default
data:
  www.conf: |
    [www]
    user = abc
    group = abc
    listen = 127.0.0.1:9000
    pm = dynamic
    pm.max_children = 120
    pm.start_servers = 12
    pm.min_spare_servers = 6
    pm.max_spare_servers = 18
