apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  namespace: default
  labels:
    name: nextcloud-data
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
    flux.weave.works/ignore: 'true'
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas2-storage.radoncanyon.com
    path: "/mnt/etank/nextcloud"
