kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-data
  namespace: default
  annotations:
    flux.weave.works/ignore: 'false'
spec:
  selector:
    matchLabels:
      name: nextcloud-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
