apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud
  namespace: default
  annotations:
    flux.weave.works/ignore: 'false'
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCklhYL7jJRCvGkNkhSArzap1GPfhnFCAjNBszUbEUOjhB09Ai8e1xJuf/5Otmy6AGpEC6fOLHd97kw6Zr7XVVkNlJLzslJ2fa5Gys3CFiOxNH3QFbbdpWvyA5S4RF2X5k+/H4nFCut6qVvvb/mfXfBD84lrqVgZWGsu3fAP9UyoAANZ2IHNazsw6D1HnIe2c0Q8wMbG3tAimb+wTOPyMuLmjnIqc97KiO405XsT9+cru6k5sNTQYAIo8dedGX4ui6k4J6yn76mPDxiq0aaU6xscepr3HJDqlnP+AJvSPt8MRAB0AEu4WjMTjVrrRwDJ9wOvW9JJGtAEfGSDkOKzHYqdRRwzPpYpoxQJGTD7hSRwVf3QcUfisECu2YdPtfmaZKiYW+hsM31c760+azW4VBbIGjVVmZCN+aiOlaGVaft5R5CPuQ+y8Yq9ymD8Ex0HSbI1M043H0dFwi8St5WnGyX2s5xMMq8lFgWixk4zehUCYa73PVxVfo2yFNGczC47HJ9FwEG5RSdUCF5SqYXacB3/0KHRtLnV+brJSGnBL4Ug7XxDXDSl65aH3ix0FQ9GbmSthWXLFE3AgKuA+AmiK0JsXGQtHmFVHVgHGIGCzxw56Zi7B8+ZsSy+/GfqPq4Ib627GeK5l0/hh1xZmrABgdC2X6oj6LMUnIHNewaTP6GNfNIS5vee+lhHDZdK2AL9jpQeWEBalCdGxNFJP8FA9JQWHgAB1A8lFEWvoqykjNID+6QFTxMYGp5BG8uz2AZ

