apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oauth2-proxy-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: oauth2-proxy
      containers:
      - name: oauth2-proxy
        image: wingedkiwi/oauth2-proxy
        volumeMounts:
        - mountPath: /etc/oauth2-proxy
          name: secret-volume
          readOnly: true
        ports:
        - containerPort: 4180
        command: ['oauth2_proxy']
        args:
          - '-config=/etc/oauth2-proxy/config'
          - '-authenticated-emails-file=/etc/oauth2-proxy/authenticated-emails'
          - '-http-address=0.0.0.0:4180'
          - '-upstream=file:///dev/null'
