apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ombi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ombi
    spec:
      nodeSelector:
        kubernetes.io/hostname: wedge.radoncanyon.com
      volumes:
      - name: ombi
        hostPath:
          path: /dockerfs/ombi/config
      containers:
      - name: ombi
        image: lsiodev/ombi-preview:latest
        volumeMounts:
        - name: ombi
          mountPath: /config
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: ombi
          containerPort: 3579
        livenessProbe:
          httpGet:
            path: /userlogin
            port: ombi
          initialDelaySeconds: 60
          periodSeconds: 5

