apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deluge
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://login.desertbluffs.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://login.desertbluffs.com/oauth2/start?rd=https://$host$escaped_request_uri"
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
spec:
  tls:
  - hosts:
    - a.desertbluffs.com
  rules:
  - host: a.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: deluge
          servicePort: deluge
