apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deluge
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
spec:
  backend:
    serviceName: deluge
    servicePort: deluge
  tls:
  - hosts:
    - a.desertbluffs.com
