apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.222.232
  externalTrafficPolicy: Local
  selector:
    app: deluge
  ports:
  - name: deluge
    port: 8112
  - name: deluge-daemon
    port: 19058
  - name: deluge-bt
    port: 22722
