---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: media
  annotations:
    flux.weave.works/tag.heimdall: glob:amd64-*-ls*
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    annotations:
      linkerd.io/inject: enabled
    spec:
      volumes:
      - name: config
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:heimdall
          targetPortal: 192.168.220.149
          lun: 1
          fsType: ext4
      containers:
      - name: heimdall
        image: linuxserver/heimdall:amd64-4980bfab-ls16
        volumeMounts:
        - name: config
          mountPath: /config
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - containerPort: 80
          name: heimdall-http
        - containerPort: 443
          name: heimdall-https
