apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: heimdall
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    external-dns.alpha.kubernetes.io/target: "desertbluffs.com"
spec:
  tls:
    - hosts:
        - heimdall.desertbluffs.com
  rules:
    - host: heimdall.desertbluffs.com
      http:
        paths:
          - path: /
            backend:
              serviceName: heimdall
              servicePort: heimdall-https
