apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: desertbluffs-com
  namespace: kube-system
spec:
  secretName: desertbluffs-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.desertbluffs.com'
  dnsNames:
  - desertbluffs.com
  - '*.desertbluffs.com'
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - '*.desertbluffs.com'
      - desertbluffs.com
