apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: default
spec:
  selector:
    app: syncthing
  type: ClusterIP
  externalIPs:
   - 10.10.10.104
  ports:
  - name: syncthing-ui
    port: 8384
    targetPort: 8384
  - name: syncthing-bt
    port: 22000
    targetPort: 22000
  - name: syncthing-disco
    port: 21027
    targetPort: 21027
    protocol: UDP

