apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: mon
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start"
spec:
  tls:
  - hosts:
    - l.desertbluffs.com
  rules:
  - host: l.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-oauth2
  namespace: mon
spec:
  tls:
  - hosts:
    - l.desertbluffs.com
  rules:
  - host: l.desertbluffs.com
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: oauth2-proxy
          servicePort: oauth2-proxy
