---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: mon
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "https://login.desertbluffs.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://login.desertbluffs.com/oauth2/start?rd=https://$host$escaped_request_uri"
spec:
  tls:
  - hosts:
    - l.desertbluffs.com
  rules:
  - host: l.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
