---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: mon
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: grafana
    servicePort: 3000
  tls:
  - hosts:
    - l.desertbluffs.com
