apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hydra2
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: hydra2
    servicePort: hydra2
  tls:
  - hosts:
    - i.desertbluffs.com
