apiVersion: v1
kind: Namespace
metadata:
  name: mon
  labels:
    name: mon
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: mon
spec:
  podSelector: {}
  policyTypes:
  - Ingress
