---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: anime
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
  selector:
    matchLabels:
      pv: anime
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
  selector:
    matchLabels:
      pv: downloads
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: movies
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
  selector:
    matchLabels:
      pv: movies
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
  selector:
    matchLabels:
      pv: tv