---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: media
  annotations:
    flux.weave.works/tag.tautulli: glob:amd64-*-ls*
    flux.weave.works/automated: 'false'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      volumes:
      - name: tautulli2
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:tautulli2
          targetPortal: 192.168.220.149
          lun: 1
          fsType: ext4
      - name: pms
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:pms-tautulli
          targetPortal: 192.168.220.149
          lun: 1
          fsType: ext4
          readOnly: true
      containers:
      - name: tautulli
        image: linuxserver/tautulli:v2.1.34-ls25
        volumeMounts:
        - name: tautulli2
          subPath: config
          mountPath: /config
        - name: pms
          subPath: config/Library/Application Support/Plex Media Server/Logs
          mountPath: /logs
          readOnly: true
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: tautulli
          containerPort: 8181
        readinessProbe:
          tcpSocket:
            port: tautulli
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: tautulli
          initialDelaySeconds: 15
          periodSeconds: 20
