---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tautulli
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: tautulli
    servicePort: tautulli
  tls:
  - hosts:
    - d.desertbluffs.com
