---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tautulli
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - d.desertbluffs.com
  rules:
  - host: d.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tautulli
          servicePort: tautulli
