apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tautulli
  namespace: media
spec:
  encryptedData:
    TAUTULLI_API_KEY: AgBLIte5zx8pOnQINdFiNtAZPbc9stYcn843sM7pJ9KkneDM9DGDW9P+InFldA9NuDiZA5OsJvvo2zqx8hvAaLdItllW0k2cJ+ljQTALAZu64XFya8bUfNGyHwKjRc6wxXP3zzz5d5LXpg5dy4hPeY2fCtKYzu1BsdCfH/K/yR18+Tpax5s+lu4M+m0m+ooRqyT46cDtqZBuRmuKPZC0/D7LzpgJZgkhWxgk24uqkscZLiUQcFs+uxteHGw2I3l3ItrgQPnJuBg1rjsO6QCQIsDqG2RCQ8Srx4NAlu9nc0RPmpHEa0ZjEeBjHGX9Sl5K1rsBM1bnRyGrng0am4yqX0nDaHHnExmZoMmdF7tz/yVRLqY33ZZwbG0CqvEVl1FvOjz4KZ4uwWD9QVqtTSpE2lSH1eDFxsXCYaIn8Zl0DhEUdn0NMdBYT+8zr46qRS21Wcu+a4rGnXfDyAqGmigjVN5L6aYkS8O6sejqHCRjQ+BnlXR6mZxOjd6agOSVwAzXRleCKGgfF+am4vK4BgaHKFOIer9Q8EC4CDgtBQ2zD2TPyNyiIqyiOK8iNDjfMH4iqBVr5/J2arSCzkahJm8NqWpjkofOUI6juE+2llU+aY2WbnYryvSLUTglqhRaLoMvM5qkeBR67QNkkVZf2X9rA/qyIXErnfmaINh8BKzTGju+pQwF0cRSkchjuTmlY9qGt4cFPugfogtrz8gsyh466lIvVoEkgFoBVx6+JYrUfT5jNA==

