---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://login.desertbluffs.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://login.desertbluffs.com/oauth2/start?rd=https://$host$escaped_request_uri"
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
spec:
  tls:
  - hosts:
    - f.desertbluffs.com
  rules:
  - host: f.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: radarr
          servicePort: radarr
