---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
  labels:
    name: pihole
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: pihole
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: pihole
  namespace: pihole
spec:
  podSelector:
    matchLabels:
      app: pihole
  ingress:
  - from: []
    ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
      - port: 67
        protocol: UDP
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  annotations:
    flux.weave.works/automated: 'false'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      volumes:
      - name: config
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:pihole
          targetPortal: 192.168.220.149
          lun: 1
          fsType: ext4
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 127.0.0.1
          - 1.1.1.2
      containers:
      - name: pihole
        image: pihole/pihole:v5.0
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - subPath: etc-pihole
          mountPath: /etc/pihole
          name: config
        - subPath: etc-dnsmasq.d
          mountPath: /etc/dnsmasq.d
          name: config
        env:
        - name: TZ
          value: 'America/New_York'
        - name: DNS1
          value: '1.1.1.2'
        - name: DNS2
          value: '1.0.0.2'
        - name: ServerIP
          value: '192.168.222.236'
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: pihole-http
          containerPort: 80
          protocol: TCP
        - name: pihole-https
          containerPort: 443
          protocol: TCP
        - name: bootp
          containerPort: 67
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.222.236
  externalTrafficPolicy: Local
  selector:
    app: pihole
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
  - name: bootp
    port: 67
    protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.222.236
  externalTrafficPolicy: Local
  selector:
    app: pihole
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: pihole-http
    port: 80
    protocol: TCP
  - name: pihole-https
    port: 443
    protocol: TCP
