---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  annotations:
    flux.weave.works/tag.sonarr: glob:amd64-3*-ls*
    flux.weave.works/automated: 'false'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:3.0.3.653-ls148
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: sonarr
          containerPort: 8989
        readinessProbe:
          tcpSocket:
            port: sonarr
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: sonarr
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: sonarr
          subPath: config
          mountPath: /config
        - name: media
          mountPath: /media
        - name: scratch
          mountPath: /downloads
          subPath: downloads
      volumes:
      - name: sonarr
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:sonarr
          targetPortal: 192.168.220.149
          lun: 1
          fsType: ext2
      - name: media
        persistentVolumeClaim:
          claimName: media
      - name: scratch
        persistentVolumeClaim:
          claimName: scratch
