---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarr
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: sonarr
    servicePort: sonarr
  tls:
  - hosts:
    - h.desertbluffs.com
