---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarr
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - h.desertbluffs.com
  rules:
  - host: h.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sonarr
          servicePort: sonarr
