---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: httpbin
  namespace: default
spec:
  serviceName: httpbin
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:

      containers:
      - name: httpbin
        image: kennethreitz/httpbin:sha256@b138b9264903f46a43e1c750e07dc06f5d2a1bd5d51f37fb185bc608f61090dd
        ports:
        - containerPort: 80
          name: httpbin

