apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: speedtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      nodeSelector:
        kubernetes.io/hostname: wedge.radoncanyon.com
      containers:
      - name: speedtest
        image: adolfintel/speedtest
        ports:
        - name: speedtest
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: speedtest
          initialDelaySeconds: 10
          periodSeconds: 5
