---
apiVersion: v1
kind: Service
metadata:
  name: knode1
  namespace: mon
spec:
  type: ExternalName
  externalName: knode1.radoncanyon.com
  ports:
    - name: netdata
      protocol: TCP
      port: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: knode2
  namespace: mon
spec:
  type: ExternalName
  externalName: knode2.radoncanyon.com
  ports:
    - name: netdata
      protocol: TCP
      port: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: nas1
  namespace: mon
spec:
  type: ExternalName
  externalName: nas1.radoncanyon.com
  ports:
    - name: netdata
      protocol: TCP
      port: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: nas2
  namespace: mon
spec:
  type: ExternalName
  externalName: nas2.radoncanyon.com
  ports:
    - name: netdata
      protocol: TCP
      port: 19999
