---
apiVersion: v1
kind: Service
metadata:
  name: knode1
  namespace: mon
  labels:
    app: netdata
spec:
  type: ExternalName
  externalName: 192.168.222.143
---
apiVersion: v1
kind: Endpoints
metadata:
  name: knode1
  namespace: mon
  labels:
    name: knode1
    app: netdata
subsets:
- addresses:
  - ip: 192.168.222.143
  ports:
  - name: netdata
    protocol: TCP
    port: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: knode2
  namespace: mon
  labels:
    app: netdata
spec:
  type: ExternalName
  externalName: knode2.radoncanyon.com
---
apiVersion: v1
kind: Endpoints
metadata:
  name: knode2
  namespace: mon
  labels:
    app: netdata
subsets:
- addresses:
  - ip: 192.168.222.144
  ports:
  - name: netdata
    protocol: TCP
    port: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: nas1
  namespace: mon
  labels:
    app: netdata-freenas
spec:
  type: ExternalName
  externalName: 192.168.222.149
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nas1
  namespace: mon
  labels:
    app: netdata-freenas
subsets:
- addresses:
  - ip: 192.168.222.149
  ports:
  - name: netdata
    protocol: TCP
    port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nas2
  namespace: mon
  labels:
    app: netdata-freenas
spec:
  type: ExternalName
  externalName: 192.168.222.114
  ports:
  - name: netdata
    protocol: TCP
    port: 19999
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nas2
  namespace: mon
  labels:
    app: netdata-freenas
subsets:
- addresses:
  - ip: 192.168.222.114
  ports:
  - name: netdata
    protocol: TCP
    port: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netdata
  namespace: mon
  labels:
    app: netdata
spec:
  selector:
    matchLabels:
      app: netdata
  endpoints:
  - port: netdata
    path: /api/v1/allmetrics
    params:
      format:
        - prometheus
    interval: 5s
    scheme: http
    honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netdata-freenas
  namespace: mon
  labels:
    app: netdata
spec:
  selector:
    matchLabels:
      app: netdata-freenas
  endpoints:
  - port: netdata
    path: /netdata/api/v1/allmetrics
    params:
      format:
        - prometheus
    interval: 5s
    scheme: http
    honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: netdata
  namespace: mon
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: netdata
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-netdata
  namespace: mon
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.5
  externalTrafficPolicy: Local
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: netdata
