---
apiVersion: v1
kind: Service
metadata:
  name: knode1
  namespace: mon
  labels:
    name: knode1
spec:
  type: ExternalName
  externalName: knode1.radoncanyon.com
  ports:
    - name: netdata
      protocol: TCP
      port: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: knode2
  namespace: mon
spec:
  type: ExternalName
  externalName: knode2.radoncanyon.com
  ports:
    - name: netdata
      protocol: TCP
      port: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: nas1
  namespace: mon
spec:
  type: ExternalName
  externalName: nas1.radoncanyon.com
  ports:
    - name: netdata
      protocol: TCP
      port: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: nas2
  namespace: mon
spec:
  type: ExternalName
  externalName: nas2.radoncanyon.com
  ports:
    - name: netdata
      protocol: TCP
      port: 19999
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: knode1
  namespace: mon
  labels:
    app: netdata
spec:
  selector:
    matchLabels:
      name: knode1
  endpoints:
  - port: netdata
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: netdata
  namespace: mon
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: netdata
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-netdata
  namespace: mon
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.5
  externalTrafficPolicy: Local
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: netdata
---
