---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pms
  namespace: media
  annotations:
    flux.weave.works/tag.pms: regexp:^([0-9]*\.?)*-[0-9a-z]*$
    flux.weave.works/automated: 'false'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pms
    spec:
      nodeSelector:
        kubernetes.io/hostname: knode1
      volumes:
      - name: pms
        hostPath:
          path: /mnt/BLOCK/pms
          type: Directory
      - name: media
        persistentVolumeClaim:
          claimName: media
      - name: transcode
        emptyDir:
          medium: Memory
      containers:
      - name: pms
        image: plexinc/pms-docker:1.15.6.1079-78232c603
        resources:
          limits:
            gpu.intel.com/i915: 1
        volumeMounts:
        - name: pms
          subPath: config
          mountPath: /config
        - name: transcode
          mountPath: /transcode
        - name: media
          mountPath: /media
          readOnly: true
        env:
        - name: CHANGE_CONFIG_DIR_OWNERSHIP
          value: 'false'
        - name: PLEX_UID
          value: '1001'
        - name: PLEX_GID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: pms
          containerPort: 32400
        - name: webtools
          containerPort: 33400
        readinessProbe:
          tcpSocket:
            port: pms
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: pms
          initialDelaySeconds: 15
          periodSeconds: 20
        lifecycle:
          postStart:
            exec:
              command: ["/bin/rm", "-f", "/usr/lib/plexmediaserver/Plex Relay"]

