---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pms
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - e.desertbluffs.com
  rules:
  - host: e.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: pms
          servicePort: 32400
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pms-webtools
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "https://login.desertbluffs.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://login.desertbluffs.com/oauth2/start?rd=https://$host$request_uri"
spec:
  tls:
  - hosts:
    - b.desertbluffs.com
  rules:
  - host: b.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: pms
          servicePort: webtools
