apiVersion: v1
kind: Service
metadata:
  name: pms
  namespace: media
spec:
  selector:
    app: pms
  type: ClusterIP
  clusterIP: 10.102.213.52
  ports:
  - name: pms
    port: 32400
    targetPort: 32400
  - name: webtools
    port: 33400
    targetPort: 33400
