apiVersion: v1
kind: Service
metadata:
  name: pms
  namespace: media
  annotations:
    # kube-router.io/service.dsr: "tunnel"
spec:
  selector:
    app: pms
  type: LoadBalancer
  externalIPs:
  - 192.168.222.241
  ports:
  - name: pms
    port: 32400
    targetPort: 32400
  - name: webtools
    port: 33400
    targetPort: 33400
