kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-data
  namespace: default
spec:
  selector:
    matchLabels:
      name: nextcloud-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
