apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchpotato
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: couchpotato
    spec:
      nodeSelector:
        kubernetes.io/hostname: biggs
      volumes:
        - name: couchpotato-config
          hostPath:
            path: /dockerfs/couchpotato/config
        - name: downloads
          hostPath:
            path: /mnt/downloads
        - name: movies
          hostPath:
            path: /mnt/media/movies
      containers:
      - name: couchpotato
        image: linuxserver/couchpotato
        volumeMounts:
        - mountPath: /config
          name: couchpotato-config
        - mountPath: /downloads
          name: downloads
        - mountPath: /movies
          name: movies
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: couchpotato
          containerPort: 5050
