apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: couchpotato
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: couchpotato.test
    http:
      paths:
      - path: /
        backend:
          serviceName: couchpotato
          servicePort: 5050
