apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser
  namespace: media
data:
  filebrowser.json: |
    {
      "port": 8080,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/data/filebrowser2.db",
      "root": "/srv",
      "auth": {
        "method": "none"
      }
    }


