apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jackett
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: jackett
    servicePort: jackett
  tls:
  - hosts:
    - g.desertbluffs.com
