apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jackett
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start"
spec:
  tls:
  - hosts:
    - g.desertbluffs.com
  rules:
  - host: g.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jackett
          servicePort: jackett
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jackett-oauth2
  namespace: media
spec:
  tls:
  - hosts:
    - g.desertbluffs.com
  rules:
  - host: g.desertbluffs.com
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: oauth2-proxy
          servicePort: oauth2-proxy
