apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr4k
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start"
spec:
  tls:
  - hosts:
    - j.desertbluffs.com
  rules:
  - host: j.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: radarr4k
          servicePort: radarr4k
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr4k-oauth2
  namespace: media
spec:
  tls:
  - hosts:
    - j.desertbluffs.com
  rules:
  - host: j.desertbluffs.com
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: oauth2-proxy
          servicePort: oauth2-proxy
