---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr4k
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: radarr4k
    servicePort: radarr4k
  tls:
  - hosts:
    - j.desertbluffs.com
