apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 192.168.222.1
      peer-asn: 64513
      my-asn: 64512
    address-pools:
    - name: LAB
      protocol: bgp
      addresses:
      - 192.168.222.230-192.168.222.250
