apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jackett
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jackett
    spec:
      nodeSelector:
        kubernetes.io/hostname: wedge.radoncanyon.com
      volumes:
      - name: jackett-config
        hostPath:
          path: /dockerfs/jackett/config
      - name: downloads-deluge-watch
        hostPath:
          path: /mnt/media/downloads/deluge/watch
      - name: localtime
        hostPath:
          path: /etc/localtime
      containers:
      - name: jackett
        image: linuxserver/jackett:latest
        volumeMounts:
        - name: jackett-config
          mountPath: /config
        - name: downloads-deluge-watch
          mountPath: /downloads
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - containerPort: 9117
          name: jackett
        livenessProbe:
          httpGet:
            path: /
            port: jackett
          initialDelaySeconds: 60
          periodSeconds: 5
