apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      nodeSelector:
        kubernetes.io/hostname: cecil.radoncanyon.com
      terminationGracePeriodSeconds: 60
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        livenessProbe:
          httpGet:
            path: /status/200
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
          name: httpbin
