apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
  annotations:
    kube-router.io/service.dsr: "tunnel"
spec:
  ports:
  - port: 8080
    targetPort: 8080
  externalIPs:
  - 10.24.85.5
  selector:
    app: httpbin
