apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: default
  annotations:
    kube-router.io/service.dsr: tunnel
spec:
  clusterIP: 10.106.216.215
  selector:
    app: pihole
  ports:
  - name: dns-tcp
    port: 53
  - name: dns-udp
    port: 53
    protocol: UDP
  - name: http
    port: 80
