apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  selector:
    k8s-app: nginx-ingress-lb
  clusterIP: 10.97.197.239
  externalIPs:
  - 10.10.10.100
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP

