apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deluge
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deluge
    spec:
      nodeSelector:
        kubernetes.io/hostname: wedge.radoncanyon.com
      volumes:
      - name: deluge
        hostPath:
          path: /dockerfs/deluge
      - name: media
        hostPath:
          path: /mnt/media
      - name: deluge-secrets
        secret:
          secretName: deluge
      containers:
      - name: deluge
        image: linuxserver/deluge:latest
        volumeMounts:
        - name: deluge
          subPath: config
          mountPath: /config
        - name: media
          subPath: downloads
          mountPath: /downloads
        - name: deluge-secrets
          subPath: auth
          mountPath: /config/auth
          readOnly: true
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - containerPort: 8112
          name: deluge
        - containerPort: 58846
          name: deluge-daemon
        - containerPort: 54199
          name: deluge-bt
        livenessProbe:
          httpGet:
            path: /
            port: deluge-webui
          initialDelaySeconds: 60
          periodSeconds: 5
