apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deluge
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deluge
    spec:
      nodeSelector:
        kubernetes.io/hostname: wedge.radoncanyon.com
      volumes:
      - name: deluge
        hostPath:
          path: /dockerfs/deluge
      - name: media
        hostPath:
          path: /mnt/media
      - name: oauth2-proxy
        secret:
          secretName: oauth2-proxy
      - name: deluge-secrets
        secret:
          secretName: deluge
      containers:
      - name: deluge
        image: linuxserver/deluge:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: deluge
          subPath: config
          mountPath: /config
        - name: media
          subPath: downloads
          mountPath: /downloads
        - mountPath: /config/auth
          name: deluge-secrets
          subPath: auth
          readOnly: true
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: deluge-webui
          containerPort: 8112
        - name: deluge-daemon
          containerPort: 54199
        livenessProbe:
          httpGet:
            path: /
            port: deluge-webui
          initialDelaySeconds: 60
          periodSeconds: 5
      - name: oauth2-proxy
        image: nlopez/oauth2_proxy
        ports:
        - name: oauth2-proxy
          containerPort: 4180
        livenessProbe:
          httpGet:
            path: /ping
            port: oauth2-proxy
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - mountPath: /etc/oauth2-proxy
          name: oauth2-proxy
          readOnly: true
        args:
        - "-upstream=http://localhost:8112/"
        - "-cookie-domain=deluge.desertbluffs.com"
        - "-redirect-url=https://deluge.desertbluffs.com/oauth2/callback"
        - "-http-address=0.0.0.0:4180"
        - "-config=/etc/oauth2-proxy/config"
        - "-authenticated-emails-file=/etc/oauth2-proxy/authenticated-emails"
        - "-cookie-secure=true"
        - "-cookie-expire=168h0m"
        - "-cookie-refresh=60m"
        - "-skip-provider-button=true"
