apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nzbget
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      nodeSelector:
        kubernetes.io/hostname: biggs.radoncanyon.com
      volumes:
      - name: nzbget
        hostPath:
          path: /dockerfs/nzbget
      - name: media
        hostPath:
          path: /mnt/media
      containers:
      - name: nzbget
        image: linuxserver/nzbget
        volumeMounts:
        - name: nzbget
          subPath: config
          mountPath: /config
        - name: nzbget
          subPath: intermediate
          mountPath: /intermediate
        - name: media
          subPath: downloads/nzbget
          mountPath: /downloads
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: nzbget
          containerPort: 6789
        livenessProbe:
          httpGet:
            path: /jsonrpc/status
            port: nzbget
          initialDelaySeconds: 60
          periodSeconds: 5

