apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nzbget
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      nodeSelector:
        kubernetes.io/hostname: biggs.radoncanyon.com
      volumes:
      - name: nzbget
        hostPath:
          path: /dockerfs/nzbget
      containers:
      - name: nzbget
        image: linuxserver/nzbget
        volumeMounts:
        - name: nzbget
          subPath: config
          mountPath: /config
        - name: nzbget
          subPath: DestDir
          mountPath: /DestDir
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: nzbget
          containerPort: 6789
        livenessProbe:
          tcpSocket:
            port: nzbget
          initialDelaySeconds: 60
          periodSeconds: 5

