apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nzbget
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: nzbget.radoncanyon.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nzbget
          servicePort: nzbget
