apiVersion: v1
kind: Service
metadata:
  name: nzbget
spec:
  selector:
    app: nzbget
  ports:
  - name: nzbget
    port: 80
    targetPort: 4180
  - name: nzbget-backend
    port: 6789
    targetPort: 6789
