apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pms
    spec:
      nodeSelector:
        kubernetes.io/hostname: biggs.radoncanyon.com
      volumes:
      - name: media
        hostPath:
          path: /mnt/media
      - name: pms
        hostPath:
          path: /dockerfs/pms
      - name: gpu
        hostPath:
          path: /dev/dri/card0
          type: CharDevice
      containers:
      - name: pms
        image: plexinc/pms-docker:public
        securityContext:
          privileged: true
        volumeMounts:
        - name: pms
          subPath: config
          mountPath: /config
        - name: gpu
          mountPath: /dev/dri/card0
        - name: media
          subPath: movies
          mountPath: /media/movies
          readOnly: true
        - name: media
          subPath: tv
          mountPath: /media/tv
          readOnly: true
        - name: media
          subPath: anime
          mountPath: /media/anime
          readOnly: true
        - name: media
          subPath: music
          mountPath: /media/music
          readOnly: true
        env:
        - name: PLEX_UID
          value: '1001'
        - name: PLEX_GID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: pms
          containerPort: 32400
        - name: webtools
          containerPort: 33400
