apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pms
    spec:
      nodeSelector:
        kubernetes.io/hostname: wedge
      volumes:
      - name: movies
        persistentVolumeClaim:
          claimName: movies
      - name: tv
        persistentVolumeClaim:
          claimName: tv
      - name: anime
        persistentVolumeClaim:
          claimName: anime
      - name: pms
        hostPath:
          path: /dockerfs/pms
      containers:
      - name: pms
        image: plexinc/pms-docker:public
        imagePullPolicy: Always
        volumeMounts:
        - name: pms
          subPath: config
          mountPath: /config
        - name: pms
          subPath: transcode
          mountPath: /transcode
        - name: movies
          mountPath: /media/movies
          readOnly: true
        - name: tv
          mountPath: /media/tv
          readOnly: true
        - name: anime
          mountPath: /media/anime
          readOnly: true
        env:
        - name: CHANGE_CONFIG_DIR_OWNERSHIP
          value: 'false'
        - name: PLEX_UID
          value: '1001'
        - name: PLEX_GID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        - name: ADVERTISE_IP
          value: http://192.168.239.7:32400,http://192.168.239.8:32400
        ports:
        - name: pms
          containerPort: 32400
        livenessProbe:
          httpGet:
            path: /web/index.html
            port: pms
          initialDelaySeconds: 60
          periodSeconds: 5
