apiVersion: v1
kind: Service
metadata:
  name: pms
spec:
  selector:
    app: pms
  type: NodePort
  ports:
  - name: pms
    port: 80
    targetPort: 32400
    nodePort: 32400
  - name: pms-backend
    port: 32400
    targetPort: 32400
