apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        kubernetes.io/hostname: cecil.radoncanyon.com
      volumes:
      - name: grafana
        hostPath:
          path: /dockerfs/grafana
      containers:
      - name: grafana
        image: grafana/grafana:4.6.2
        volumeMounts:
        - name: grafana
          subPath: data
          mountPath: /var/lib/grafana
        env:
        - name: GF_SERVER_ROOT_URL
          value: https://m.desertbluffs.com
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: 'true'
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: 'true'
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        ports:
        - name: grafana
          containerPort: 3000
