apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shaarli
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
  - hosts:
    - n.desertbluffs.com
  rules:
  - host: n.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: shaarli
          servicePort: shaarli
