---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.1.0
  values:
    controller:
      kind: DaemonSet
      config:
        global-auth-url: "https://login.desertbluffs.com/oauth2/auth"
        global-auth-signin: "https://login.desertbluffs.com/oauth2/start?rd=https://$host$escaped_request_uri"
      extraArgs:
        default-ssl-certificate: "ingress-nginx/desertbluffs-tls"
