---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.1.0
  values:
    controller:
      service:
        annotations:
          external-dns.alpha.kubernetes.io/target: "desertbluffs.com"
      kind: DaemonSet
      config:
        global-auth-url: "https://login.desertbluffs.com/oauth2/auth"
        global-auth-signin: "https://login.desertbluffs.com/oauth2/start?rd=https://$host$escaped_request_uri"
        hsts: "false"
        hsts-include-subdomains: "false"
        ssl-protocols: "TLSv1.3"
        ssl-session-cache: "false" # set via server-snippet
        ssl-session-tickets: "false"
        enable-ocsp: "true"
        server-tokens: "false"
        server-snippet: |
          ssl_session_timeout 1d;
          ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
          proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
      extraArgs:
        default-ssl-certificate: "ingress-nginx/desertbluffs-tls"
