apiVersion: v1
kind: Service
metadata:
  name: thelounge
  namespace: default
spec:
  selector:
    app: thelounge
  type: LoadBalancer
  loadBalancerIP: 192.168.10.3
  externalTrafficPolicy: Local
  ports:
  - name: thelounge
    port: 9000
    targetPort: 9000
  - name: identd
    port: 113
    targetPort: 113

