apiVersion: v1
kind: Service
metadata:
  name: thelounge
  namespace: default
spec:
  selector:
    app: thelounge
  type: ClusterIP
  clusterIP: 10.102.89.130
  ports:
  - name: thelounge
    port: 9000
    targetPort: 9000
  - name: identd
    port: 113
    targetPort: 113

