---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: emby
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-global-auth: "false"
spec:
  tls:
  - hosts:
    - k.desertbluffs.com
  rules:
  - host: k.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: emby
          servicePort: 8096
