apiVersion: v1
kind: Service
metadata:
  name: emby
  namespace: media
  annotations:
    # kube-router.io/service.dsr: "tunnel"
spec:
  selector:
    app: emby
  type: ClusterIP
  externalIPs:
  - 10.10.10.102
  ports:
  - name: emby-https
    port: 8920
    targetPort: 8920

