apiVersion: v1
kind: Service
metadata:
  name: unifi
spec:
  selector:
    app: unifi
  type: NodePort
  ports:
  - name: unifi
    port: 8443
  - name: unifi-backend
    port: 8080
    nodePort: 31311

