apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web
  namespace: default
spec:
  encryptedData:
    SECRET_KEY_BASE: AgCoHXeNuaC+d09KXvOEfYALmcvmiPLcq4M97VGb9X7EMGc92ZynXzkgalhTljzFV0fNzi5eia7GM0zSHO0RszF9o8c7fty1A402eXlxtl5ZmMydmt5qpJWrtR8EMEyPGI12obYswieGSMiR5xF/7H5myqdptBDGbhfC4LmTPNLaezod7+xt9QruvydOLGFeEyr3K5AtsJOJmBsEeQzCOemOdSfYm2xm8PLOIDMWgfoQgFM+YZlburgnshRY8A5gQoJqFisZaRXRYGPglrf82OuNwppn+hgvMi//jKryQjBnCS+FubTLHG98ZW8DJgrWgIFcWTmwnt4mSAANFr4TMsR1udyJ+t6nXmx7zJeWPZbsOi9hPbLV3LSjtSQ4SbL63viqBoMFMTXG3cPV9XLLwhhxihCUD5FlW83qKJEnYX+3IKnQpNGGelLVHa04LXGsD792l3wC/uk2bNf+9Qs9FBut0LyrsePHAQzoVlEshIpEKTtcxGeOtNXqxSXugTmP4VMYzsdqvQm+Ijvc7dC5PUdJSVR//2Gw38pXDc3+TSt7xZ3p6L7Hlz1VG+0lMzb55rm7QoPrKSQkOabM/fDR3uJuKgcSX1/ZfehZkG3QF09B9QlsFge7JCm1rU+vWT/LJ4K91kXt9wIg18tu+6rHjhCWQpWAuJq0Zv8qeBrtSYaOBOJPuPAwrSgKmCJ4lmg/CyTAYX1TCEjgdiY0z7/Ft6h9RV1d0kH5nk//H87G7m7CK0NbtqnzzOmoBdJXhm2ch7VyopAahUjBvHj1UpmN6wGcNnsCZ8R0KfadCd9hTLRXbYOu/PggzoeSTxDFl5lU+xe0NXgwc5lat2MXO0ASJYMRigzFfAQBhBzKzT5eNJJwGQ==
