apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  namespace: media
  labels:
    name: media
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.114
    path: "/mnt/etank/media"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scratch
  namespace: media
  labels:
    name: scratch
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.149
    path: "/mnt/etank/scratch"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: roms
  namespace: media
  labels:
    name: roms
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.149
    path: "/mnt/etank/scratch/roms"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge
  namespace: media
  labels:
    name: deluge
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.149
    path: "/mnt/etank/scratch/downloads/deluge"
