apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  namespace: media
  labels:
    name: media
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas2-storage.radoncanyon.com
    path: "/mnt/etank/media"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-nas1
  namespace: media
  labels:
    name: downloads-nas1
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas1-storage.radoncanyon.com
    path: "/mnt/etank/scratch/downloads"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge
  namespace: media
  labels:
    name: deluge
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas1-storage.radoncanyon.com
    path: "/mnt/etank/scratch/downloads/deluge"
