kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  namespace: media
spec:
  selector:
    matchLabels:
      name: media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-nas1
  namespace: media
spec:
  selector:
    matchLabels:
      name: downloads-nas1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-nas2
  namespace: media
spec:
  selector:
    matchLabels:
      name: downloads-nas2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: music-nas2
  namespace: media
spec:
  selector:
    matchLabels:
      name: music-nas2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deluge
  namespace: media
spec:
  selector:
    matchLabels:
      name: deluge
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
