apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plexpy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plexpy
    spec:
      nodeSelector:
        kubernetes.io/hostname: wedge.radoncanyon.com
      volumes:
      - name: plexpy
        hostPath:
          path: /dockerfs/plexpy
      - name: pms
        hostPath:
          path: /dockerfs/pms
      containers:
      - name: plexpy
        image: linuxserver/plexpy:latest
        volumeMounts:
        - name: plexpy
          subPath: config
          mountPath: /config
        # - name: pms
        #   subPath: config/Library/Application Support/Plex Media Server/Logs
        #   mountPath: /logs
        #   readOnly: true
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: plexpy
          containerPort: 8181
        livenessProbe:
          httpGet:
            path: /home
            port: plexpy
          initialDelaySeconds: 60
          periodSeconds: 5
