apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plexpy
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - plexpy.desertbluffs.com
    secretName: plexpy-tls
  rules:
  - host: plexpy.desertbluffs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: plexpy
          servicePort: 80

