apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgCV3jLys5di13BZYZF9XBLR8AbUpyGSx45MEpVU1gQL6sqpjvLgHtw2g6BUejE6JzjQ1eAfPEoJM2d2e/PDUbt82FRgQiVEUzzMyJ2ZEZyD3WlVtC/Gb1ND+HLHaG4Bw3l5RKawMcZmoG/oHUMnAIMd4M7oYvu+alWZySod5/4QlH9r4tbpEAl51ST6ziZ5W2SSlEwOFcY1gGjgPvnpZ+9ml0YFjfzWHXqRlAPTnLb8Y+EYn8ihqsRsXinxtkZeR2LDQsHzyGSs5LllIxWiWOj0jJ8Kny5cjAxdn6l3Xrt4Ra82yK4J5dpYddWLy2qmL7w/G5XuB/wOZPQxgB+nqp76Br5qT1MxKsJxg+umo5MQVOBhuzy4Mfg2PUHPXjJAMtBQ5X/sjBaleH7tkHQskN/ITD7Gjwo8TobNQcef8kAA2yIDHe+6zcypaCGpc2ixONfY0xEgAwCNr4pyZj7WGZI3X1tINYg2dKOU1/Deu5AEkMzDQT/mXkLvKgvpAqfN4+inb3IygAE/0pRwtjOpKPYqN3iMQGAzw3kLVl/Xij8U1Vr200hoSfpiZ9JeE/qr0u9MP8SGXWvfp73LuhoY0KDIkjZrgD8ivAlbV1H1pkJzJsN6Qo0cyqas0ZV2uZTGUDHNxnmaG3OMWs382DxUxio4lz6rtxPLv1LXEzMSIhui35k6xOqjcEIkyNLQ2v0n+I5GhWiQjG1q66fQzDQ44oQ8jC9dHzkKjWT1hxRXGWjeJTlYFWW/

