apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "nlopez@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-private-key
    dns01:
      providers:
      - name: route53
        route53:
          region: us-east-1
          accessKeyID: AKIAITMMOBOC4DLKJAUQ
          hostedZoneID: Z3KB4M5M0P7MCT
          secretAccessKeySecretRef:
            name: route53-config
            key: secret-access-key
