apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:
        kubernetes.io/hostname: cecil.radoncanyon.com
      volumes:
      - name: prometheus
        hostPath:
          path: /dockerfs/prometheus
      securityContext:
        runAsUser: 1001
      containers:
      - name: prometheus
        image: prom/prometheus:v2.0.0
        args: [
          "--config.file=/config/prometheus.yml",
          "--storage.tsdb.path=/prometheus-data",
          "--web.console.libraries=/etc/prometheus/console_libraries",
          "--web.console.templates=/etc/prometheus/consoles"
        ]
        volumeMounts:
        - name: prometheus
          subPath: config
          mountPath: /config
        - name: prometheus
          subPath: data
          mountPath: /prometheus-data
        ports:
        - name: prometheus
          containerPort: 9090
