---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-unicorn-l
  namespace: media
  annotations:
    flux.weave.works/automated: 'false'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pms-unicorn
  template:
    metadata:
      labels:
        app: pms-unicorn
    spec:
      nodeSelector:
        kubernetes.io/hostname: knode1
      volumes:
      - name: pms-unicorn
        hostPath:
          path: /mnt/BLOCK/pms-unicorn
          type: Directory
      - name: media
        persistentVolumeClaim:
          claimName: media
      - name: transcode
        emptyDir:
          medium: Memory
      containers:
      - name: pms-unicorn
        image: nlopez/unicorn-transcoder:3
        # resources:
        #   limits:
        #     gpu.intel.com/i915: 1
        volumeMounts:
        - name: pms-unicorn
          subPath: config
          mountPath: /config
        - name: transcode
          mountPath: /transcode
        - name: media
          mountPath: /media
          readOnly: true
        env:
        - name: CHANGE_CONFIG_DIR_OWNERSHIP
          value: 'false'
        - name: PLEX_UID
          value: '1001'
        - name: PLEX_GID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        - name: CUSTOM_SERVERS_LIST
          value: 'http://pms-unicorn-0.pms-unicorn:3000/,http://pms-unicorn-1.pms-unicorn:3000/'
        - name: REDIS_HOST
          value: 'pms-unicorn-redis'
        - name: LOADBALANCER_ADDRESS
          value: 'https://k.desertbluffs.com'
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: unicorn-lb
          containerPort: 3001
        readinessProbe:
          tcpSocket:
            port: unicorn-lb
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: unicorn-lb
          initialDelaySeconds: 15
          periodSeconds: 20
        lifecycle:
          postStart:
            exec:
              command: ["/bin/rm", "-f", "/usr/lib/plexmediaserver/Plex Relay"]
